ccde_cmd: don't fail when switchName or landbHcpNextServer is not in json
Signed-off-by: Adam Wujek <adam.wujek@cern.ch>

diff --git a/ccde_cmd b/ccde_cmd
--- a/ccde_cmd
+++ b/ccde_cmd
@@ -14,8 +14,9 @@ tmp_path="/tmp"
 tmp_name=$(mktemp -u  $tmp_path/wrs.XXXXXX)
 tmp_json="$tmp_name"-json
 cat > "$tmp_json"
-device_name_tmp=`cat "$tmp_json" | grep "switchName"`
-boot_server_tmp=`cat "$tmp_json" | grep "landbHcpNextServer"`
+# "|| true" to avoid failing when json is missing item
+device_name_tmp=`cat "$tmp_json" | grep "switchName" || true`
+boot_server_tmp=`cat "$tmp_json" | grep "landbHcpNextServer" || true`
 if [ -n "$device_name_tmp" ]; then
     IFS=":, " read -r x device_name <<< $device_name_tmp
     # strip quotas
@@ -29,7 +30,7 @@ else
     exit 1
 fi
 
-if [ -n "boot_server_tmp" ]; then
+if [ -n "$boot_server_tmp" ] || [ "$boot_server_tmp" = "null" ]; then
     IFS=":, " read -r x boot_server <<< $boot_server_tmp
     # strip quotas
     boot_server=${boot_server//\"/}
